#!/usr/bin/env bash
# This script is displaying "Best School" 10 but says 'Hi' after the 9th iteration.
a="0"
while [ $x -lt 10 ]
do
	echo "Best School"
	if ((a==8))
	then
		echo "Hi"
	fi
	a=$((a+1))
done
