#!/usr/bin/env bash
#loop 10 iterations using while loop and conditional statement.
a="0"
while [ $a -lt 10 ]
do 
	if ((a==3))
	then
		echo "bad luck"
	elif((a==7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((a++))
done
