#!/usr/bin/env bash
#loop 20 iterations and also display
# bad luck from China for the 4th loop iteration
# bad luck from Japan for the 9th loop iteration
# then bad luck from Italy for the 17th loop iteration

i="0"

while [ $i -le 20 ]
do
	echo "$i"
	case $i in 
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((i++))
done
